Repository KTH-DD2480-Fundsoft/assignment-2, pull requests merged in 2024-02, with the labels that each got.

#8 Feature/1/first draft project structure
  .gitignore
  README.md
  doc/img/structure.png
Labels: documentation

#14 feat: Flask skeleton
  ci_server/server.py
  test_ci_server/test_server.py
Labels: enhancement

#18 Add logic for the CI server
  .gitignore
  ci_server/ci_logic.py
  ci_server/test_runner.py
  test_ci_server/test_compilation.py
Labels: 2 needs: correction

#19 feat: add webhook functionality
  ci_server/ci_logic.py
  ci_server/server.py
  test_ci_server/test_server.py
Labels: 1 type: feature

#20 feat: add GitHub API function, tests and documentation
  ci_server/GitHub_API_functions.py
  doc/GitHubAPI.md
  test_ci_server/test_GitHub_API_functions.py
Labels: 1 type: feature

#47 feat: connect CI logic with GH API
  ci_server/ci_runner.py
Labels: 1 type: feature

#55 feat: add correct CI server url to commit status
  ci_server/GitHub_API_functions.py
  test_ci_server/test_GitHub_API_functions.py
Labels: 1 type: enchancement

#61 fix: server tests to use new hashing for authkey
  ci_server/server.py
  test_ci_server/test_server.py
Labels: 1 type: bugfix

#62 fix: suppress stout when running compileall.compile_dir
  ci_server/ci_runner.py
  test_ci_server/test_compilation.py
Labels: 1 type: bugfix

#67 refactor: cleanup Github_API_functions.py
  ci_server/GitHub_API_functions.py
  ci_server/__init__.py
Labels: 1 type: refactor
